/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AplikasiPenjualan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC RPL - R1
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form paymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t36RadioButton = new javax.swing.JRadioButton();
        t45RadioButton = new javax.swing.JRadioButton();
        t54RadioButton = new javax.swing.JRadioButton();
        buildingPriceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        largeLandTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        availableLandTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        installmentAmountTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        installmentMonthTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        agreementCbx = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesanan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        priceLandTxt.setEditable(false);
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "Bougenvile", "Melati ", "Flamboyan" }));
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Bangunan");

        jLabel6.setText("Tipe Rumah");

        radioButton.add(t36RadioButton);
        t36RadioButton.setText("Tipe - 36");
        t36RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36RadioButtonActionPerformed(evt);
            }
        });

        radioButton.add(t45RadioButton);
        t45RadioButton.setText("Tipe - 45");
        t45RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t45RadioButtonActionPerformed(evt);
            }
        });

        radioButton.add(t54RadioButton);
        t54RadioButton.setText("Tipe - 54");
        t54RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t54RadioButtonActionPerformed(evt);
            }
        });

        buildingPriceTxt.setEditable(false);
        buildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Luas Tanah Asli");

        largeLandTxt.setEditable(false);
        largeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Luas Tanah Tersedia");

        availableLandTxt.setEditable(false);
        availableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPn (10%)");

        jLabel13.setText("Cicilan/Bulan");

        totalPriceTxt.setEditable(false);
        totalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        installmentAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        installmentMonthTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Bulan");

        agreementCbx.setText("Setuju");
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });

        saveButton.setText("SIMPAN");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("HAPUS");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        processButton.setText("PROSES");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiPenjualan/rumah.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(orderNameTxt)
                                .addComponent(priceLandTxt)
                                .addComponent(areaCombobox, 0, 144, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(t36RadioButton)
                            .addComponent(t45RadioButton)
                            .addComponent(t54RadioButton)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87))
                                .addComponent(largeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(installmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addComponent(installmentMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(processButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(agreementCbx)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t36RadioButton)
                    .addComponent(largeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t45RadioButton)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addComponent(t54RadioButton)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(installmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(installmentMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processButton)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(agreementCbx))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
       switch(areaCombobox.getSelectedIndex()) {
           case 0:
               priceLandTxt.setText("");
               buildingPriceTxt.setText("");
               radioButton.clearSelection();
                largeLandTxt.setText("");
    availableLandTxt.setText("");
    totalPriceTxt.setText("");
    DPTxt.setText("");
    installmentAmountTxt.setText("");
    installmentMonthTxt.setText("");
    ppnTxt.setText("");
    agreementCbx.setSelected(false);
               break;
               
               case 1:
               priceLandTxt.setText("500000");
               buildingPriceTxt.setText("90000000");
               radioButton.clearSelection();
                largeLandTxt.setText("");
    availableLandTxt.setText("");
    totalPriceTxt.setText("");
    DPTxt.setText("");
    installmentAmountTxt.setText("");
    installmentMonthTxt.setText("");
    ppnTxt.setText("");
    agreementCbx.setSelected(false);
               break;
               
               case 2:
               priceLandTxt.setText("600000");
               buildingPriceTxt.setText("120000000");
               radioButton.clearSelection();
                largeLandTxt.setText("");
    availableLandTxt.setText("");
    totalPriceTxt.setText("");
    DPTxt.setText("");
    installmentAmountTxt.setText("");
    installmentMonthTxt.setText("");
    ppnTxt.setText("");
    agreementCbx.setSelected(false);
               break;
               
                default:
               priceLandTxt.setText("700000");
               buildingPriceTxt.setText("150000000");
               radioButton.clearSelection();
               largeLandTxt.setText("");
               availableLandTxt.setText("");
               totalPriceTxt.setText("");
               DPTxt.setText("");
               installmentAmountTxt.setText("");
               installmentMonthTxt.setText("");
               ppnTxt.setText("");
               agreementCbx.setSelected(false);
               break;
       }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void t36RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36RadioButtonActionPerformed
      if(areaCombobox.getSelectedIndex() == 0) {
           JOptionPane.showConfirmDialog(null, "Pilih area terlebih dahulu");
           radioButton.clearSelection();
       } else {
           largeLandTxt.setText("90");
           availableLandTxt.setText("54");
           long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                   totalPrice;
           totalPrice = (availableLand * landPrice)+ buildingPrice;
           totalPriceTxt.setText("" + totalPrice);
           
installmentAmountTxt.setText("");
           DPTxt.setText("");
           ppnTxt.setText("");
           installmentMonthTxt.setText("");
       } 
    }//GEN-LAST:event_t36RadioButtonActionPerformed

    private void t45RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t45RadioButtonActionPerformed
       if(areaCombobox.getSelectedIndex() == 0) {
           JOptionPane.showConfirmDialog(null, "Pilih area terlebih dahulu");
           radioButton.clearSelection();
       } else {
           largeLandTxt.setText("120");
           availableLandTxt.setText("75");
           long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                   totalPrice;
           totalPrice = (availableLand * landPrice)+ buildingPrice;
           totalPriceTxt.setText("" + totalPrice);
               installmentAmountTxt.setText("");  
           DPTxt.setText("");
           ppnTxt.setText("");
           installmentMonthTxt.setText("");
       } 
    }//GEN-LAST:event_t45RadioButtonActionPerformed

    private void t54RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t54RadioButtonActionPerformed
        if(areaCombobox.getSelectedIndex() == 0) {
           JOptionPane.showConfirmDialog(null, "Pilih area terlebih dahulu");
           radioButton.clearSelection();
       } else {
           largeLandTxt.setText("140");
           availableLandTxt.setText("86");
           long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                   totalPrice;
           totalPrice = (availableLand * landPrice)+ buildingPrice;
           totalPriceTxt.setText("" + totalPrice);
           
            installmentAmountTxt.setText("");
           DPTxt.setText("");
           ppnTxt.setText("");
           installmentMonthTxt.setText("");
       } 
    }//GEN-LAST:event_t54RadioButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    orderNameTxt.setText("");
        priceLandTxt.setText("");
        areaCombobox.setSelectedIndex(0);
        radioButton.clearSelection();
        buildingPriceTxt.setText("");
        largeLandTxt.setText("");
        availableLandTxt.setText("");
        totalPriceTxt.setText("");
        DPTxt.setText("");
        installmentAmountTxt.setText("");
        ppnTxt.setText("");
        installmentMonthTxt.setText("");
        agreementCbx.setSelected(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
      if(totalPriceTxt.getText().isEmpty()){
          JOptionPane.showConfirmDialog(null, "Pilihan belum lengkap");
      } else if(DPTxt.getText().isEmpty()) {
          JOptionPane.showConfirmDialog(null, "DP harus diisi");
      } else if (installmentAmountTxt.getText().isEmpty()) {
          JOptionPane.showConfirmDialog(null, "Isi jumlah cicilan yang diinginkan");
      } else {
          long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                  dp = Long.parseLong(DPTxt.getText()),
                  installmentAmount = Long.parseLong(installmentAmountTxt.getText()),
                  totalPrice, ppn, installmentMonth;
                  totalPrice = (availableLand * landPrice)+ buildingPrice;
                  ppn = totalPrice * 10 / 100;
                  installmentMonth = (totalPrice * ppn) / installmentAmount;
                  ppnTxt.setText("" + ppn);
                  installmentMonthTxt.setText("" + installmentMonth);
      }
    }//GEN-LAST:event_processButtonActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if(orderNameTxt.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Nama Pemesanan harus diisi");
                        agreementCbx.setSelected(false);
        } else if( ppnTxt.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Tekan tombol proses terlebih dahulu");
            agreementCbx.setSelected(false);
        } else if(agreementCbx.isSelected() == true) {
            JOptionPane.showConfirmDialog(null, "Pemesan menyetujui");
                        agreementCbx.setSelected(true);
        } else{
            JOptionPane.showConfirmDialog(null, "Pemesanan belum disetujui");
                        agreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementCbxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(agreementCbx.isSelected() == false) {
            JOptionPane.showConfirmDialog(null, "Klik centang checkbox untuk simpan data", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String typeHouse;
            if (t36RadioButton.isSelected()) {
             typeHouse = "TIPE 36";   
            } else if (t45RadioButton.isSelected()) {
        typeHouse = "TIPE 45";
        } else {
                typeHouse = " TIPE 54";
            }
            try {
            String sql = "INSERT INTO rumah (name, area, tipe, luas, harga, jumlah_cicilan, cicilan_bulan) VALUES (?, ?, ?, ?, ?, ?, ?)";
            Connection conn = (Connection) ConnectionDb.connectDatabase();
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, orderNameTxt.getText());
            pst.setString(2, areaCombobox.getSelectedItem().toString());
            pst.setString(3, typeHouse);
            pst.setString(4, largeLandTxt.getText());
            pst.setString(5, totalPriceTxt.getText());
            pst.setString(6, installmentAmountTxt.getText());
            pst.setString(7, installmentMonthTxt.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");

            OptionMenu optionMenu = new OptionMenu();
            optionMenu.setVisible(true);
            this.getDesktopPane().add(optionMenu);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPTxt;
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JTextField availableLandTxt;
    private javax.swing.JTextField buildingPriceTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField installmentAmountTxt;
    private javax.swing.JTextField installmentMonthTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField largeLandTxt;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton processButton;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton t36RadioButton;
    private javax.swing.JRadioButton t45RadioButton;
    private javax.swing.JRadioButton t54RadioButton;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
